---
- name: Install sqlite3
  ansible.builtin.apt:
    name: sqlite3
    state: present

- name: Create /db directory
  file:
    path: /db
    state: directory

- name: Copy SQLite bootstrap
  copy:
    src: bootstrap.sql
    dest: /db/bootstrap.sql
    mode: 0644

- name: Create invoicer DB
  shell: |
    sqlite3 /db/invoicer.db < /db/bootstrap.sql

