---
- name: Create a User to use to run Ansible Playbooks
  user:
    name: ansible
    state: present
    groups: sudo
    shell: /bin/bash
    password: "*" # Lock the account, allowing access only through SSH.

- name: Copy over the public key from the GitHub runner to allow access.
  authorized_key:
    user: ansible
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

# Need to also lock down the root user here.
