---
- name: Create a User to use to run Ansible Playbooks
  ansible.builtins.user:
    name: ansible
    state: present
    groups: wheel
    shell: /bin/bash
    password: "*" # Lock the account, allowing access only through SSH.

# Need to also lock down the root user here.
