---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true

- name: Install docker-ce
  become: yes
  ansible.builtin.apt:
    name: docker-ce=5:20.10.22~3-0~ubuntu-focal
    state: present
    update_cache: true
