---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - always

- name: Add Docker Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true
  tags:
    - always

- name: Install docker-ce
  become: yes
  ansible.builtin.apt:
    name: docker-ce=5:20.10.22~3-0~ubuntu-focal
    state: present
    update_cache: true
  tags:
    - always

- name: Start Docker CE
  service:
    name: docker
    state: started
    user: docker
  tags:
    - always

- name: Create a User to use to run Docker
  become: yes
  ansible.builtin.user:
    name: docker
    state: present
    groups: sudo, docker
    shell: /bin/bash
    password: "*" # Lock the account, allowing access only through SSH.
  notify:
    - Start Docker CE
  tags:
    - always

- name: Pull application image
  become: yes
  community.general.docker_image:
    name: ghcr.io/alexmackechnie/invoicer:latest
    source: pull
  tags:
    - always

- name: Start Container
  become: yes
  ansible.builtin.shell: |
    . /sec/setup.sh
    docker stop invoicer || true
    docker run \
      --rm -d \
      -p 5001:5001 \
      -v /db/invoicer.db:/db/invoicer.db \
      -e ENV="prod" \
      -e FLASK_APP_SECRET_KEY=${FLASK_APP_SECRET_KEY} \
      -e GITLAB_CLIENT_SECRET=${GITLAB_CLIENT_SECRET} \
      --name invoicer \
      ghcr.io/alexmackechnie/invoicer:latest
  tags:
    - always

