---
- name: Add Docker GPG apt Key
  always: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  always: yes
  become: yes
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
    update_cache: true

- name: Install docker-ce
  always: yes
  become: yes
  ansible.builtin.apt:
    name: docker-ce=5:20.10.22~3-0~ubuntu-focal
    state: present
    update_cache: true

- name: Create a User to use to run Docker
  become: yes
  ansible.builtin.user:
    name: docker
    state: present
    groups: sudo, docker
    shell: /bin/bash
    password: "*" # Lock the account, allowing access only through SSH.
  always: yes
  notify:
    - Start Docker CE

- name: Pull application image
  become: yes
  always: yes
  community.general.docker_image:
    name: ghcr.io/alexmackechnie/invoicer:latest
    source: pull
  notify:
    - Start Container

