name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./api
      run: python -m build

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag invoicer:$(date +%s)
