name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build the Docker image
      working-directory: ./api
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install build
        python -m build
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --file Dockerfile --tag invoicer:$(date +%s)
