name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build the Docker image
      working-directory: ./api
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install build
        python -m build
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker image
      working-directory: ./api
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/alexmackechnie/invoicer:${TAG}
        docker push ghcr.io/alexmackechnie/invoicer:${TAG}

