name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build the Docker image
      working-directory: ./api
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install build
        python -m build
        #    - name: Build the Docker image
        #      working-directory: ./api
        #      run: docker build . --file Dockerfile --tag invoicer:$(date +%s)
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      working-directory: ./api
      with:
        registry: ghrc.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      working-directory: ./api
      with:
        context: ./api/.
        push: true
        tags: alexmackechnie/invoicer:latest
